# serverless.yml

service: alexjpazdotcom

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  # @see https://github.com/dougmoscrop/serverless-http/issues/88
  # @see https://github.com/serverless/serverless/pull/6063
  apiGateway:
    binaryMediaTypes:
      - 'image/*'

package:
  excludeDevDependencies: true
  exclude:
    - "packages/**"

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  status_check:
    handler: status_check.handler
    events:
      - schedule: rate(15 minutes)
