# serverless.yml

service: alexjpazdotcom

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

package:
  excludeDevDependencies: true

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
