#!/bin/bash

CMD=$1
shift
ARGS=$@

deploy() {
  docker pull xueshanf/awscli
  docker run --rm \
   -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
   -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
   -e AWS_DEFAULT_REGION=us-east-1 \
   -v $PWD:/app xueshanf/awscli\
    aws s3 cp \
      --recursive \
      --content-type "text/plain" \
      --cache-control "max-age=3600" \
      /app/public \
      s3://alexjpaz.com
}

$CMD $ARGS
