#!/bin/bash

CMD=$1
shift
ARGS=$@

build() {
  echo "it built"
}

_aws() {
  docker run --rm \
   -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
   -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
   -e AWS_DEFAULT_REGION=us-east-1 \
   -v $PWD:/app xueshanf/awscli\
    aws $@
}

put_website_config() {
    _aws s3api put-bucket-website --bucket alexjpaz.com --website-configuration file://website.config
}

deploy() {
  docker pull xueshanf/awscli
  put_website_config
  _aws s3 cp \
      --recursive \
      --content-type "text/html" \
      --cache-control "max-age=61" \
      --acl public-read \
      /app/public \
      s3://alexjpaz.com
}

$CMD $ARGS
